---
title: "Visuals"
author: "andrés castro araújo"
date: "`r format(Sys.Date(), '%b %d, %Y')`"
output: 
  html_document: 
    theme: paper
    toc: yes
    toc_float:
      collapsed: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = "", fig.align = "center")

library(tidyverse)

theme_custom <- function() {
  theme_minimal(base_family = "IBM Plex Sans") +
  theme(
    plot.title = element_text(face = "bold"),
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(size = 0.2),
    strip.background = element_rect(fill = "gray80", color = "gray80")
  ) 
}
```

```{css, echo=FALSE}
blockquote {
    padding: 10px 20px;
    margin: 0 0 20px;
    font-size: 14px;
    color: #828282;
    border-left: 10px solid #EEE;
}

body {
    font-size: 14px;
}
```



```{r}
path <- list.files("data", pattern = "Summary", full.names = TRUE)
sheets <- readxl::excel_sheets(path)

## Total Mentions
# readxl::read_excel(path, sheet = sheets[[1]], n_max = 2, skip = 1, range = "A2:D3") 
```

```{r}
df <- readxl::read_excel(path, sheet = sheets[[3]], n_max = 118, 
                         col_types = c("text", "numeric", "numeric"))

df <- df %>% 
  mutate(date = as.Date(`Publication Date (GMT-05:00) New York`, "%b %d, %Y")) %>% 
  filter(date < as.Date("2020-01-01"))
```

```{r, fig.width=10, fig.height=6}
g <- df %>% 
  pivot_longer(cols = c(Mentions, Posts), names_to = "type", values_to = "count") %>% 
  ggplot() + 
  geom_rect(aes(xmin = as.Date("2019-09-15"), xmax = as.Date("2019-09-22"), 
                ymin = 0, ymax = Inf), alpha = 0.1, fill = "grey80") +
  geom_line(aes(date, count, linetype = fct_rev(type))) +
  theme_custom() +
  scale_y_continuous(labels = scales::comma) +
  scale_x_date(date_labels = "%b, %Y", date_breaks = "4 months") +
  labs(x = NULL, linetype = NULL, caption = "\nSource: Netbase", 
       title = "Posts and Mentions on Social Media (Weekly)",
       subtitle = '"Climate Change" OR "Global Warming"') + 
  theme(legend.position = "top") 

g + annotate("text", x = as.Date("2019-05-01"), y = 3e6, 
             label = "Climate Week      \nSeptember 23-29", size = 3) +
    geom_curve(aes(x = as.Date("2019-06-01"), xend = as.Date("2019-09-01"), 
                   y = 2.8e6, yend = 2.8e6), size = 0.5,
               arrow = arrow(length = unit(0.15, "cm"))) 

ggsave("count_timeline.png", device = "png", dpi = "print", width = 10, height = 6)
```

```{r}

library(ggseas)
g <- df %>% 
  #filter(lubridate::year(date) >= 2018) %>% 
  ggsdc(aes(date, Mentions), frequency = 12, method = "stl", s.window = 50) +
  geom_line() + 
  theme_custom()

  
df$pred <- g$data %>% 
  filter(component == "trend") %>% 
  pull(y)


df %>%
  ggplot(aes(x = date)) + 
  geom_line(aes(y = pred, color = "predicted"), alpha = 0.5) +
  geom_line(aes(y = Mentions, color = "observed")) +
  scale_y_continuous(labels = scales::comma) + 
  theme_custom() +
  scale_color_manual(values = c("black", "tomato"))
```


```{r, fig.width=10}
g <- df %>% 
  select(-`Publication Date (GMT-05:00) New York`, -pred) %>% 
  mutate(month = lubridate::floor_date(date, "month")) %>% 
  group_by(month) %>% 
  filter(n() >= 3) %>% 
  summarize(mentions = sum(Mentions), posts = sum(Posts)) %>% 
  pivot_longer(cols = c(mentions, posts), names_to = "type", values_to = "count") %>% 
  ggplot(aes(month, count)) + 
  geom_col(show.legend = FALSE) + 
  facet_wrap(~type, ncol = 1) + 
  theme_custom() +
  scale_x_date(date_labels = "%b, %Y", date_breaks = "3 months") +
  scale_y_continuous(labels = scales::comma) +
  labs(x = NULL, linetype = NULL, caption = "\nSource: Netbase", 
       title = "Posts and Mentions on Social Media (Monthly)",
       subtitle = '"Climate Change" OR "Global Warming"') 


g + geom_col(data = g$data %>% filter(month == as.Date("2019-09-01")),
             fill = "steelblue1", width = 25)

ggsave("count_monthly.png", device = "png", dpi = "print", width = 10, height = 6)

```

```{r}
df %>% 
  select(-`Publication Date (GMT-05:00) New York`, -pred) %>% 
  mutate(month = lubridate::floor_date(date, "month")) %>% 
  group_by(month) %>% 
  filter(n() >= 3) %>% 
  summarize(mentions = sum(Mentions), posts = sum(Posts)) %>% 
  mutate(prev = lag(mentions)) %>% 
  mutate(g = scales::percent((mentions / prev) - 1)) %>% 
  View()
```



```{r}
sept <- df %>% 
  select(-`Publication Date (GMT-05:00) New York`, -pred) %>% 
  mutate(month = lubridate::floor_date(date, "month")) %>% 
  filter(month == "2019-09-01")


sept %>% 
  mutate(mentions_one_week = (Mentions / lag(Mentions)) - 1,
         mentions_two_week = (Mentions / lag(Mentions, 2)) - 1) %>% 
  na.omit() %>% 
  mutate(mentions_one_week = scales::percent(mentions_one_week),
         mentions_two_week = scales::percent(mentions_two_week))
```

During Climate Week: 

- social media mentions increased by 56%, from the previous week.

- social media mentions increased by 192%, from two weeks before.


```{r}
df %>% 
  select(-`Publication Date (GMT-05:00) New York`, -pred) %>% 
  mutate(month = lubridate::month(date, label = TRUE)) %>% 
  filter(month == "Sep") %>% 
  mutate(year = lubridate::year(date)) %>% 
  group_by(year) %>% 
  mutate(id = row_number()) %>% 
  filter(id < 5) %>% 
  ggplot(aes(id, Mentions, color = year %>% as.character())) + 
  geom_line() +
  labs(color = NULL, y = "Mentions\n", x = "\nWeek of September",
       title = "Social Media Mentions", subtitle = "Sept 2018 vs Sept 2019",
       caption = "\nSource: Netbase") +
  scale_y_continuous(labels = scales::comma) + 
  theme_custom() +
  theme(legend.position = "top")

ggsave("count_septembers.png", device = "png", dpi = "print", width = 10, height = 6)

```


September of 2019:

- social media mentions increased by 50%, from the previous month

- social media mentions increased by 243%, from september of 2018


```{r}
df %>% 
  select(-`Publication Date (GMT-05:00) New York`, -pred) %>% 
  mutate(month = lubridate::month(date, label = TRUE)) %>% 
  filter(month == "Sep") %>% 
  mutate(year = lubridate::year(date)) %>% 
  group_by(year, month) %>% 
  summarize(Mentions = sum(Mentions))

(9262627	/ 2696006	) - 1



df %>% 
  select(-`Publication Date (GMT-05:00) New York`, -pred) %>% 
  mutate(month = lubridate::month(date, label = TRUE)) %>% 
  filter(month == "Sep") %>% 
  mutate(year = lubridate::year(date)) %>% 
  group_by(year) %>% 
  mutate(id = row_number())


(2981596 / 394958) - 1
```

